builds:
  - binary: terraform-provider-auth0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    "386": 32-bit
    darwin: macOS
    linux: Tux
