builds:
  - binary: terraform-provider-auth0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archive:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
