dist: trusty
sudo: required

services:
- docker

language: go
go:
  - "1.12.x"

cache:
  directories:
  - $GOPATH/pkg/mod

env:
  - GO111MODULE=on

install:
  # This script is used by the Travis build to install a cookie for
  # go.googlesource.com so rate limits are higher when using `go get` to fetch
  # packages that live there.
  # See: https://github.com/golang/go/issues/12933
  - bash scripts/gogetcookie.sh
  # This script installs Code Climate test coverage reporter.
  # See: https://docs.codeclimate.com/docs/travis-ci-test-coverage
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /home/travis/bin/cc-test-reporter
  - chmod +x /home/travis/bin/cc-test-reporter

before_script:
  - cc-test-reporter before-build

script:
  - make build
  - make testacc OPTS=-coverprofile=c.out
  - make website-test

after_script:
  - cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: script
  script: bash scripts/release.sh $TRAVIS_TAG
  on:
    tags: true

branches:
  only:
    - master
    # - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
