[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[[constraint]]
  name = "github.com/yieldr/go-auth0"
  version = "v1.0.0-beta.8"

[prune]
  go-tests = true
  unused-packages = true
