name: Build
on: 
  push:
    branches: ['*']
    paths-ignore:
      - '**.md'
      - 'example/**'
      - 'website/**'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out source
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Set up Git cookies
      run: bash scripts/gogetcookie.sh

    - name: Build
      run: make build

    - name: Test
      run: make testacc OPTS=-coverprofile=c.out
      env:
        AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Send code coverage report
      uses: aktions/codeclimate-test-reporter@v1
      with:
        codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
        command: after-build --prefix github.com/alexkappa/terraform-provider-auth0
