name: Label

on: [pull_request]

jobs:
  label:
    name: Label
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.LABELER_TOKEN }}"