name: Release
on: 
  push:
    tags: ['*']

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Get version from ref
      run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)
      id: get_version
      
    - name: Go release
      run: ./scripts/release.sh ${{ steps.get_version.outputs.VERSION }}

    # - name: Go release
    #   uses: goreleaser/goreleaser-action@v1
    #   with:
    #     version: ${{ steps.get_version.outputs.VERSION }}
    #     args: --skip-validate --release-notes="${TMPDIR}/release-notes.md"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}